openapi: 3.0.0
info:
  title: LED Controller API
  description: API pour contrôler une bande LED via un serveur web hébergé sur un ESP8266. Chaque route permet de configurer les paramètres des LED, tels que l'état, la luminosité, la vitesse, les couleurs et les modes d'éclairage.
  version: 1.1.0
servers:
  - url: http://{host}
    description: Serveur local pour accéder à l'API
    variables:
      host:
        default: 192.168.1.189
        description: Adresse IP du serveur configurée sur l'ESP8266.

paths:
  /api/health:
    get:
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: string