name: Deploy on GitHub Pages
on:
  push:
    branches: [ "feature/basics_api" ]
  workflow_dispatch:

    
permissions:
  contents: write
  id-token: write
  deployments: write
  pages: write 

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Interface to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: V2/interface

      - name: Build project for GitHub Pages
        run: npm run build:githubpage
        working-directory: V2/interface

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: V2/interface/dist
          publish_branch: gh-pages